# This is a config for E2B sandbox template.
# You can use template ID (airu52t5fob60zfdzm8i) or template name (vibe-nextjs-vinh-test) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("vibe-nextjs-vinh-test") # Sync sandbox
# sandbox = await AsyncSandbox.create("vibe-nextjs-vinh-test") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('vibe-nextjs-vinh-test')

team_id = "27ba6fd2-d57b-42c3-a871-abd9dbc088eb"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "vibe-nextjs-vinh-test"
template_id = "airu52t5fob60zfdzm8i"
